pipeline:
  build:
    image: klakegg/hugo:ext-debian-ci
    commands:
      - hugo

  deploy:
    image: debian
    commands:
      - mkdir ~/.ssh && chmod -R 700
      - apt update -y && apt install openssh-client rsync -y
      - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
      - echo 'echo "$SSH_PASSPHRASE"' > ~/.ssh/.print_ssh_password
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=":0.0" SSH_ASKPASS=~/.ssh/.print_ssh_password setsid ssh-add - > /dev/null
      - rsync -atv --delete --progress public/ backy@backy.cybershell.xyz:docs
      - rsync -atv --delete --progress vangen/ backy@backy.cybershell.xyz:vangen-go

branches: master